# Generated by Django 3.2.8 on 2021-10-25 00:26

import appraisal.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_auto_20211023_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'jpg', 'jpeg', 'png'])])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), appraisal.models.max_value_current_year])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price Range')),
                ('engine_no', models.CharField(max_length=255, verbose_name='Engine #')),
                ('manufacture_year', models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), appraisal.models.max_value_current_year], verbose_name='Year of Manufacture')),
                ('engine_and_trans', models.CharField(max_length=255, verbose_name='Engine and Transmission')),
                ('interior', models.CharField(max_length=255, verbose_name='Interior')),
                ('exterior', models.CharField(max_length=255, verbose_name='Exterior')),
                ('suspension', models.CharField(max_length=255, verbose_name='Suspension')),
                ('safety', models.CharField(max_length=255, verbose_name='Safety')),
                ('other_features', models.CharField(max_length=255, verbose_name='Other Features')),
                ('documents', models.ManyToManyField(to='appraisal.Document', verbose_name='Documents')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.manufacturer')),
                ('pics', models.ManyToManyField(to='appraisal.Pic', verbose_name='Pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Note')),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.document', verbose_name='')),
            ],
        ),
    ]
