# Generated by Django 3.2.8 on 2021-10-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0004_auto_20211024_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chasis_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chasis #'),
        ),
    ]
