# Generated by Django 3.2.8 on 2021-10-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0006_auto_20211025_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.pic', verbose_name='Brand Image'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Image Title'),
        ),
    ]
