# Generated by Django 3.2.8 on 2021-10-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0007_auto_20211025_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
