# Generated by Django 3.2.8 on 2021-10-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0009_alter_manufacturer_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='chasis_no',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chassis #'),
        ),
    ]
